### ISSUE TITLE
Velociraptor loader not working consistently

### ISSUE THREAD

**Issue by R3dP1ll** [fox-it/dissect.target#548] opened 2024-02-20 14:56 UTC
Hello
When performing collections with velociraptor (Kape.Target.Files pluging for example), I noticed that some plugins don't work like
usnjrnl, regf, mft to name a few.
I tried to troubleshoot it and inserted the following print in /opt/homebrew/lib/python3.11/site-packages/dissect/target/plugins/filesystem/ntfs/usnjrnl.py
<img width="443" alt="Screenshot 2024-02-20 at 15 52 57" src="https://github.com/fox-it/dissect.target/assets/6017124/75a4b65f-753b-4cf0-b822-3e15aabb53d0">
But I was surprised to see some non deterministic behavior that I can't explain when running **target-query -f usnjrnl Collection-WIN10-2024-02-15T20_41_37_01_00/ -q** twice in a row. and the number of filesystems would change after each run

Can you let me know if it is expected first please?

**Comment by R3dP1ll** [comment] 2024-02-20 14:57
Closed

**Comment by Schamper** [comment] 2024-02-20 15:49
Hi @R3dP1ll, thank you for the report. I'm not sure if the closure was accidental or not. Either way, could you provide some more information on how exactly you ran the Velociraptor acquisition? We don't use Velociraptor ourselves, so we'd need some information in order to reproducde. Or if you have a test file available, it would be great if you could share that!

**Comment by R3dP1ll** [comment] 2024-02-20 17:41
Hello
I closed it because I realised I pasted the wrong code for the behavior I wanted to enquire about.
it was actually in line 59 of /opt/homebrew/lib/python3.11/site-packages/dissect/target/loaders/dir.py.
I inserted a print statement right after **print(target.filesystems)** and so when I run target-query -f usnjrnl Collection-WIN10-2024-02-15T20_41_37_01_00/ I would get different values everytime I run the command and the number of filesystems discovered changes from run to run.

The main issue I wanted to raise is that some plugins of target-query don't run correctly with velociraptor collections. I 
[Collector_velociraptor-v0.7.0-windows-amd64.exe.zip](https://github.com/fox-it/dissect.target/files/14349237/Collector_velociraptor-v0.7.0-windows-amd64.exe.zip)
I have attached the velociraptor offline collector (https://docs.velociraptor.app/docs/offline_triage/). I understand if you hesitate to run it so let me know so that I can prepare an environment with no sensitive data that could show in the output.

**Comment by Schamper** [comment] 2024-02-20 21:26
Thanks for the triage, that's pretty interesting behavior that we'll have to fix. Unsure what the cause is so we'll need to dig into that.

@Zawadidone by any chance have you ever encountered this before?

**Comment by Zawadidone** [comment] 2024-02-21 18:00
> I found the problem. It's a MacOs thingie because of the .DS_Store that gets created. This stops processing. Once deleted, the loader works as predicted and plugins work. I added this in **/opt/homebrew/lib/python3.11/site-packages/dissect/target/loaders/dir.py** line 52. for path in dirs: if ".DS_Store" in str(path): continue Thank you !

I guess that after extracting the ZIP file, the file `.DS_Store` is created in the folder that contains volumes e.g. `uploads/ntfs_vss/.DS_Store`.

This is could be fixed by checking if the path is a directory in https://github.com/fox-it/dissect.target/blob/502d16bb81b78856fe633a0cba86e511d5c188cc/dissect/target/loaders/velociraptor.py#L45.

**Comment by Zawadidone** [comment] 2024-02-21 18:10
@R3dP1ll could you verify if this fixes the issue https://github.com/fox-it/dissect.target/commit/a510d7e12405283f4e1c66a4d454d67e044dc946?

**Comment by R3dP1ll** [comment] 2024-02-21 19:47
Hello
I added the fix in my code and tried to play with it to see if the behavior still happens.
<img width="1440" alt="image" src="https://github.com/fox-it/dissect.target/assets/6017124/b0dc7893-7e04-46bc-9e92-ba178d32218c">

<img width="1418" alt="image" src="https://github.com/fox-it/dissect.target/assets/6017124/62479159-1089-414c-8927-bc25c3e18365">

Regarding my environment, I am now in a virtual one with only dissect installed. The non deterministic behavior still occurs however as you can see between multiple runs of the exact same command

**Comment by R3dP1ll** [comment] 2024-02-21 20:02
<img width="1429" alt="image" src="https://github.com/fox-it/dissect.target/assets/6017124/a9193c4d-0be5-4c46-b2b5-4c045b617670">
it shows clearly here

**Comment by R3dP1ll** [comment] 2024-02-21 20:56
![image](https://github.com/fox-it/dissect.target/assets/6017124/5dc82f80-bc52-4712-8516-52e5bca9dc6b)
the order with which the volumes are processed could be important? it appears that if the C drive is last then problems start.
<img width="216" alt="image" src="https://github.com/fox-it/dissect.target/assets/6017124/80fd975c-e3b2-48e2-8bbf-aecce3467572">
My collection has these two because of some etl files. For now I will try to force the C drive to always be first on the list

**Comment by Zawadidone** [comment] 2024-02-21 21:12
The loader only supports the usage of a single accessor, the image shows that the two accessors ‘ntfs’ and ‘auto’ are used at the same time which will not work.

I will share the Velociraptor collector configuration that is supported by the loader, to clarify the usage of the loader.

What Velociraptor hunt configuration did you use to create the collector

**Comment by R3dP1ll** [comment] 2024-02-21 21:18
I just saw the warning so I guess it is expected then.
For now I did a little hack to force the C: to be the first volume to be loaded as I guessed the plugin detect functions do not tolerate any failure to load a volume and just die, but you know the internals better. 
![image](https://github.com/fox-it/dissect.target/assets/6017124/32f90599-fc30-4866-9d68-afaed6009d3d)

For velociraptor this is the config
<img width="683" alt="image" src="https://github.com/fox-it/dissect.target/assets/6017124/817c583c-46a8-4cea-8de8-c6f41ec332b5">

**Comment by Zawadidone** [comment] 2024-02-22 09:23
The configuration shown in the image is not supported by the Velociraptor loader. Could you create the collector with the following configuration for the artifact `Windows.KapeFiles.Target` and verify if the loader works?

`{"Windows.KapeFiles.Targets":{"VSSAnalysisAge":"1000","_SANS_Triage":"Y"}}`

**Comment by R3dP1ll** [comment] 2024-02-29 06:03
Indeed. So I just "force" the loading of the C disk first everytime and now it works, even with the ntfs folder (another accessor). A hacky way but works for me now

Thank you for your time!

**Closed** 2024-02-29 06:04 UTC
